services:
  - type: worker
    name: eliza-worker
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    nodeVersion: 23.3.0
    plan: standard
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - packages/**
        - package.json
        - pnpm-lock.yaml
        - turbo.json
        - .nvmrc
    disk:
      name: eliza-cache
      mountPath: /opt/render/project/src/.turbo
      sizeGB: 1
    cache:
      - name: pnpm-cache
        mountPath: /opt/render/project/src/.pnpm-store
        key: pnpm-store-{{ checksum "pnpm-lock.yaml" }}
      - name: turbo-cache
        mountPath: /opt/render/project/src/.turbo
        key: turbo-cache-{{ checksum "turbo.json" }}-{{ checksum "pnpm-lock.yaml" }}
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80
    resources:
      memory: 2048
      cpu: 1000 