services:
  - type: worker
    name: eliza-worker
    env: node
    buildCommand: |
      if [ -d ".pnpm-store" ]; then
        echo "Using cached dependencies"
        pnpm install --offline --frozen-lockfile --prod
      else
        echo "Installing dependencies"
        pnpm install --frozen-lockfile --prod
      fi
      pnpm install typescript @types/node --save-dev
      pnpm run build
      rm -rf node_modules/.cache
      rm -rf node_modules/@types
      rm -rf node_modules/typescript
    startCommand: node dist/src/index.js
    nodeVersion: 23.3.0
    plan: standard
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: >-
          --max-old-space-size=3072
          --expose-gc
          --optimize-for-size
          --gc-interval=100
          --max-semi-space-size=256
          --heapsnapshot-near-heap-limit=3
          --optimize-for-size
          --no-global-gc-scheduling
          --no-incremental-marking
          --max-heap-size=3072
          --initial-heap-size=2048
      - key: V8_MAX_OLD_SPACE_SIZE
        value: "3072"
      - key: V8_HEAP_SIZE_MB
        value: "3072"
      - key: V8_MAX_SEMI_SPACE_SIZE_IN_MB
        value: "256"
      - key: UV_THREADPOOL_SIZE
        value: "4"
      - key: CHARACTER_FILE
        value: characters/production.character.json
      # Database Configuration
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      # Model Provider Configuration
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ORG_ID
        sync: false
      # Client Configuration
      - key: DISCORD_APPLICATION_ID
        sync: false
      - key: DISCORD_API_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      # Voice Configuration
      - key: ELEVENLABS_XI_API_KEY
        sync: false
      - key: ELEVENLABS_MODEL_ID
        value: eleven_multilingual_v2
      - key: ELEVENLABS_VOICE_ID
        value: 21m00Tcm4TlvDq8ikWAM
      - key: ELEVENLABS_VOICE_STABILITY
        value: "0.5"
      - key: ELEVENLABS_VOICE_SIMILARITY_BOOST
        value: "0.9"
      - key: ELEVENLABS_VOICE_STYLE
        value: "0.66"
      - key: ELEVENLABS_VOICE_USE_SPEAKER_BOOST
        value: "false"
      - key: ELEVENLABS_OPTIMIZE_STREAMING_LATENCY
        value: "4"
      - key: ELEVENLABS_OUTPUT_FORMAT
        value: pcm_16000
    autoDeploy: false
    buildFilter:
      paths:
        - packages/**
        - package.json
        - pnpm-lock.yaml
        - turbo.json
        - .nvmrc
        - characters/**
        - tsconfig.json
        - src/**
        - config/**
    disk:
      name: eliza-cache
      mountPath: /opt/render/project/src/.turbo
      sizeGB: 5
    cache:
      - name: pnpm-store
        mountPath: /opt/render/project/src/.pnpm-store
        key: pnpm-store-{{ checksum "pnpm-lock.yaml" }}
      - name: turbo-cache
        mountPath: /opt/render/project/src/.turbo
        key: turbo-cache-{{ checksum "turbo.json" }}-{{ checksum "pnpm-lock.yaml" }}
      - name: node-modules
        mountPath: /opt/render/project/src/node_modules
        key: node-modules-{{ checksum "pnpm-lock.yaml" }}
      - name: dist
        mountPath: /opt/render/project/src/dist
        key: dist-{{ checksum "tsconfig.json" }}-{{ checksum "src/**/*.ts" }}-{{ checksum "config/**/*.ts" }}
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 70
      targetCPUPercent: 80
    resources:
      memory: 4096
      cpu: 1000
    healthCheckPath: /health
    healthCheckTimeout: 100
    gracePeriodSeconds: 60
    restartPolicyType: OnFailure
    restartPolicyMaxRetries: 5
    preBootCommand: |
      node -e "
      const used = process.memoryUsage();
      for (let key in used) {
        console.log(`${key}: ${Math.round(used[key] / 1024 / 1024 * 100) / 100} MB`);
      }
      " 