services:
  - type: worker
    name: eliza-worker
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    nodeVersion: 23.3.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - packages/**
        - package.json
        - pnpm-lock.yaml
        - turbo.json
        - .nvmrc 